version: "3"

vars:
  REPO: "tobiashochguertel/vscode-settings-updater"

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task --list

  build:
    desc: "Build extension with esbuild"
    cmds:
      - pnpm build

  watch:
    desc: "Watch mode — rebuild on change"
    cmds:
      - pnpm watch

  lint:
    desc: "Run ESLint"
    cmds:
      - pnpm lint

  format:
    desc: "Run Prettier"
    cmds:
      - pnpm format

  test:
    desc: "Run Vitest unit tests"
    cmds:
      - pnpm test

  test:e2e:
    desc: "Run E2E tests in VS Code Extension Host (requires display / xvfb)"
    cmds:
      - pnpm test:e2e

  package:
    desc: "Create .vsix package"
    cmds:
      - pnpm package

  check-size:
    desc: "Traffic-light VSIX size check (🟢 ≤10% / 🟡 10-50% / 🔴 >50% → fail)"
    cmds:
      - node scripts/check-package-size.mjs

  update-size-baseline:
    desc: "Update the VSIX size baseline after an intentional size change"
    cmds:
      - task: package
      - node scripts/check-package-size.mjs --update

  install-local:
    desc: "Install .vsix into local VS Code"
    cmds:
      - code --install-extension *.vsix

  debug:
    desc: "Launch VS Code Extension Host for debugging (requires 'code' CLI in PATH)"
    cmds:
      - code --extensionDevelopmentPath={{.ROOT_DIR}} --new-window

  publish:
    desc: "Publish extension to VS Code Marketplace (requires VSCE_PAT env var)"
    cmds:
      - pnpm publish
